homeassistant:
  # Name of the location where Home Assistant is running
  name: 之家
  # Location required to calculate the time the sun rises and sets
  latitude: 37.8267
  longitude: -122.4233
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 24
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai

  customize:
    sensor.forecastio_apparent_temperature:
      friendly_name: 体感温度
    sensor.cpu_use:  
      friendly_name: CPU使用率
    sensor.forecastio_cloud_coverage:
      friendly_name: 天气云量
    sensor.forecastio_daily_high_temperature:
      friendly_name: 最高温度
    sensor.forecastio_daily_low_temperature:
      friendly_name: 最低温度
    sensor.forecastio_humidity:
      friendly_name: 天气湿度
    sensor.forecastio_icon:
      friendly_name: 天气概况
    sensor.forecastio_summary:
      friendly_name: 天气现况
    sensor.forecastio_temperature:
      friendly_name: 实时温度
    sensor.forecastio_visibility:
      friendly_name: 能见度
    sensor.forecastio_wind_bearing:
      friendly_name: 风向
    sensor.forecastio_wind_speed:
      friendly_name: 风速
    sensor.ram_use: 
      friendly_name: RAM使用率
    sun.sun:
      friendly_name: 日出日落 时间
    switch.Sonoff_WoShi_2:
      friendly_name: 客厅开关
    switch.Sonoff_WoShi_1:
      friendly_name: 卧室开关
    sensor.ws2_temperature:
      friendly_name: 客厅温度
    sensor.ws2_humidity:
      friendly_name: 客厅湿度
     

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#MQTT服务器的相关设置，除了username和password，没搞懂之前，别瞎改
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: ############
  password: #########
  protocol: 3.1.1
#开关1：Sonoff开关（客厅）
switch:
  platform: mqtt
  name: "Sonoff_WoShi_2"
  state_topic: "home/Bed_room/1/stat"
  command_topic: "home/Bed_room/1/"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true  
#开关2，预留 卧室开关  
switch 2:  
  platform: mqtt
  name: "Sonoff_WoShi_1"
  state_topic: "home/Bed_room/ws2/stat"
  command_topic: "home/Bed_room/ws2/"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true  
  
# 传感器1：天气“传感器”，API请到forecast.io网站注册并获得，然后填写好
sensor:
  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'WS_Temperature'
    unit_of_measurement: '°C'
    #value_template: 'temperat
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'WS_Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'
    
  - platform: mqtt
    state_topic: 'home/Bed_room/1/sensor'
    name: 'KT_Temperature'
    unit_of_measurement: '°C'
    #value_template: 'temperat
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'home/Bed_room/1/sensor'
    name: 'KT_Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'     

  - platform: mqtt
    state_topic: 'home/Bed_room/ws2/sensor'
    name: 'WS2_Temperature'
    unit_of_measurement: '°C'
    #value_template: 'temperat
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'home/Bed_room/ws2/sensor'
    name: 'WS2_Humidity'    
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'     
    
#传感器2：树莓派硬件“监测器”，楼主只使用了两项：CPU占用率和RAM使用率      
sensor 2:      
  - platform: systemmonitor
    resources:
    # - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    # - type: since_last_boot
    

